// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'entities/collection_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 3183681213699536948),
    name: 'CollectionEntity',
    lastPropertyId: const obx_int.IdUid(5, 5229324932148646097),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7375666918894158515),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3002100662775018942),
        name: 'strMeal',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 309213241950697075),
        name: 'strMealThumb',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7852723670070014130),
        name: 'idMeal',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5229324932148646097),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 3183681213699536948),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CollectionEntity: obx_int.EntityDefinition<CollectionEntity>(
      model: _entities[0],
      toOneRelations: (CollectionEntity object) => [],
      toManyRelations: (CollectionEntity object) => {},
      getId: (CollectionEntity object) => object.id,
      setId: (CollectionEntity object, int id) {
        object.id = id;
      },
      objectToFB: (CollectionEntity object, fb.Builder fbb) {
        final strMealOffset = object.strMeal == null
            ? null
            : fbb.writeString(object.strMeal!);
        final strMealThumbOffset = object.strMealThumb == null
            ? null
            : fbb.writeString(object.strMealThumb!);
        final idMealOffset = object.idMeal == null
            ? null
            : fbb.writeString(object.idMeal!);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, strMealOffset);
        fbb.addOffset(2, strMealThumbOffset);
        fbb.addOffset(3, idMealOffset);
        fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final object = CollectionEntity(id: idParam, createdAt: createdAtParam)
          ..strMeal = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 6)
          ..strMealThumb = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 8)
          ..idMeal = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 10);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CollectionEntity] entity fields to define ObjectBox queries.
class CollectionEntity_ {
  /// See [CollectionEntity.id].
  static final id = obx.QueryIntegerProperty<CollectionEntity>(
    _entities[0].properties[0],
  );

  /// See [CollectionEntity.strMeal].
  static final strMeal = obx.QueryStringProperty<CollectionEntity>(
    _entities[0].properties[1],
  );

  /// See [CollectionEntity.strMealThumb].
  static final strMealThumb = obx.QueryStringProperty<CollectionEntity>(
    _entities[0].properties[2],
  );

  /// See [CollectionEntity.idMeal].
  static final idMeal = obx.QueryStringProperty<CollectionEntity>(
    _entities[0].properties[3],
  );

  /// See [CollectionEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<CollectionEntity>(
    _entities[0].properties[4],
  );
}
